In [2]:
import numpy as np


In [2]:
c = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [5]:
c[0:2, -1]

array([3, 6])

In [4]:
c[0:1,-1]

array([3])

In [3]:
k = np.array([[3,8,4],[9,3,5],[11,15,17],[19,31,8]])
k

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [4]:
k.shape

(4, 3)

In [5]:
m = np.array([[[4,8,7],[3,1,5],[6,9,13]],[[41,81,71],[31,11,51],[61,91,131]]])
m

array([[[  4,   8,   7],
        [  3,   1,   5],
        [  6,   9,  13]],

       [[ 41,  81,  71],
        [ 31,  11,  51],
        [ 61,  91, 131]]])

In [6]:
m.shape

(2, 3, 3)

In [7]:
m = np.array([[[4,8,7],[3,1,5]],[[6,9,13],[41,81,71]],[[31,11,51],[61,91,131]]])
m

array([[[  4,   8,   7],
        [  3,   1,   5]],

       [[  6,   9,  13],
        [ 41,  81,  71]],

       [[ 31,  11,  51],
        [ 61,  91, 131]]])

In [8]:
m.shape

(3, 2, 3)

In [9]:
m = np.array([[[4,41],[8,81],[7,71]],[[3,31],[1,11],[5,51]],[[6,61],[9,91],[13,131]]])
m

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [10]:
m.shape

(3, 3, 2)

In [11]:
k

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [12]:
# indexing
k[1][0]

9

In [13]:
# subscripting
k[1,0]

9

In [14]:
k[2]

array([11, 15, 17])

In [15]:
k[2:]

array([[11, 15, 17],
       [19, 31,  8]])

In [16]:
k[2,]

array([11, 15, 17])

In [17]:
k[2,0:]

array([11, 15, 17])

In [18]:
k[2,0:3:1]

array([11, 15, 17])

In [19]:
k[0:4,-2]

array([ 8,  3, 15, 31])

In [20]:
k[0:,-2]

array([ 8,  3, 15, 31])

In [21]:
k[:,-2]

array([ 8,  3, 15, 31])

In [22]:
m

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [23]:
k[:,1:2]

array([[ 8],
       [ 3],
       [15],
       [31]])

In [24]:
m

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [25]:
m[0:2]

array([[[ 4, 41],
        [ 8, 81],
        [ 7, 71]],

       [[ 3, 31],
        [ 1, 11],
        [ 5, 51]]])

In [26]:
m[0:2,0]

array([[ 4, 41],
       [ 3, 31]])

In [27]:
m[0:2,1:]

array([[[ 8, 81],
        [ 7, 71]],

       [[ 1, 11],
        [ 5, 51]]])

In [28]:
m[0:2,1:,0]

array([[8, 7],
       [1, 5]])

In [29]:
m[:2,-2:,:1]

array([[[8],
        [7]],

       [[1],
        [5]]])

In [30]:
m

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [31]:
m[-1:,-2:,:]

array([[[  9,  91],
        [ 13, 131]]])

In [32]:
k


array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [33]:
k[0,0] = 99

In [34]:
k

array([[99,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [35]:
k[0:,-2:-1]

array([[ 8],
       [ 3],
       [15],
       [31]])

In [38]:
k[0:,-2:-1] = 777

In [39]:
k

array([[ 99, 777,   4],
       [  9, 777,   5],
       [ 11, 777,  17],
       [ 19, 777,   8]])

In [40]:
for i in range(4):
    k[i:,-2:-1] = i

In [41]:
k


array([[99,  0,  4],
       [ 9,  1,  5],
       [11,  2, 17],
       [19,  3,  8]])

In [42]:
k[:,1] = [45,46,47,48]

In [43]:
k

array([[99, 45,  4],
       [ 9, 46,  5],
       [11, 47, 17],
       [19, 48,  8]])

In [44]:
b-5

NameError: name 'b' is not defined

In [45]:
k-5

array([[94, 40, -1],
       [ 4, 41,  0],
       [ 6, 42, 12],
       [14, 43,  3]])

In [46]:
k

array([[99, 45,  4],
       [ 9, 46,  5],
       [11, 47, 17],
       [19, 48,  8]])

In [47]:
np.append(k,[[1,1,1]], axis = 0) # row

array([[99, 45,  4],
       [ 9, 46,  5],
       [11, 47, 17],
       [19, 48,  8],
       [ 1,  1,  1]])

In [48]:
k

array([[99, 45,  4],
       [ 9, 46,  5],
       [11, 47, 17],
       [19, 48,  8]])

In [49]:
k = np.append(k,[[1,1,1]], axis = 0)

In [50]:
k

array([[99, 45,  4],
       [ 9, 46,  5],
       [11, 47, 17],
       [19, 48,  8],
       [ 1,  1,  1]])

In [54]:
np.append(k,[[1],[1],[1],[1],[1]], axis = 1) # column


array([[99, 45,  4,  1],
       [ 9, 46,  5,  1],
       [11, 47, 17,  1],
       [19, 48,  8,  1],
       [ 1,  1,  1,  1]])

In [57]:
k = np.delete(k,-1, axis = 1)

In [58]:
k

array([[99, 45],
       [ 9, 46],
       [11, 47],
       [19, 48],
       [ 1,  1]])

In [ ]:
# Array creation functions
# np.array()
# np.arrange()
# np.linspace()
# np.ones()
# np.zeros()
# np.eye()
# np.random.randint()
