In [ ]:
# pip install opencv-python
# pip install scikit-image
# pip install matplotlib

In [2]:
import numpy as np


In [3]:
np.arrange(1,11,1)

AttributeError: module 'numpy' has no attribute 'arrange'

In [4]:
#prints the numbers from (arg1,arg2,arg3) arg1 to arg2 by taking a gap of arg3
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [6]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.arange(1,11,1.25)

array([1.  , 2.25, 3.5 , 4.75, 6.  , 7.25, 8.5 , 9.75])

In [8]:
# lispace is used to print from 1 to 10 but only 5 numbers
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [9]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.linspace(1,11,6)

array([ 1.,  3.,  5.,  7.,  9., 11.])

In [11]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [13]:

np.ones(4)

array([1., 1., 1., 1.])

In [14]:
# print ones in the list of 4x5 matrix
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
# print zeros in the matrix of 4x5
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
# print ones in the diagonal and zeros otherwise in matrix of size 4x4
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.ones([4,5], dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
np.random.randint(1,100,1)

array([92])

In [20]:
# generate 5 random number between 1 to 100
np.random.randint(1,100,5)

array([ 4,  7, 11,  4, 85])

In [21]:
np.random.randint(1,100,[3,5])

array([[76, 37, 86, 86, 94],
       [73, 93, 93, 94, 87],
       [22, 63, 38, 76, 50]])

In [22]:
# seed is used to repeat the pattern of the random numbers generated
# same pattern of numbers will be generated whenever seed is given value of 500
np.random.seed(500)
np.random.randint(1,100,5)

array([91, 56, 66, 18, 79])

In [23]:
np.random.seed(500)
np.random.randint(1,100,5)

array([91, 56, 66, 18, 79])

In [24]:
np.random.randint(1,100,5)

array([62, 32, 73, 72, 78])

In [26]:
# generate random numbers from 0.0 to 1.0
np.random.rand(3,4)

array([[0.21054571, 0.36548743, 0.15075393, 0.29093556],
       [0.69427792, 0.03862193, 0.89562247, 0.7915128 ],
       [0.0553974 , 0.29615787, 0.07993204, 0.73414449]])

In [27]:
# generate random negative numbers too
np.random.randn(3,4)

array([[-0.07828685, -0.1481367 ,  0.57426852, -0.01451292],
       [ 1.49185618,  0.76446885,  0.91269279, -0.73679107],
       [ 0.80113828, -0.18959264,  0.02146429,  1.27784448]])

In [28]:
import random

In [31]:
np.loadtxt('data.txt', dtype='str')

array([['this', 'is', 'a', 'new', 'file'],
       ['Here', 'we', 'get', 'some', 'data']], dtype='<U4')

In [32]:
np.loadtxt('data1.txt', delimiter=',')

array([[  1.,   2.,   3.,   4.],
       [ 11.,  22.,  33.,  44.],
       [111., 222., 333., 444.]])

In [33]:
# delimiter defines the seperater that seperates the elements
np.loadtxt('data1.txt', delimiter=';')

array([[  1.,   2.,   3.,   4.],
       [ 11.,  22.,  33.,  44.],
       [111., 222., 333., 444.]])

In [39]:
np.savetxt('data3.txt',a, delimiter='|',fmt='%d')

In [40]:
a = np.random.randint(1,100,[3,4])

In [41]:
a

array([[54, 54, 39, 34],
       [73, 71, 46, 64],
       [76, 12, 90, 24]])

In [42]:
np.savetxt('data3.txt',a, delimiter='|',fmt='%d')


In [44]:
np.loadtxt('data3.txt',delimiter='|')

array([[54., 54., 39., 34.],
       [73., 71., 46., 64.],
       [76., 12., 90., 24.]])

In [45]:
a.sum()

637

In [46]:
sum(a)

array([203, 137, 175, 122])

In [47]:
sum(sum(a))

637

In [49]:
# gives sum of elements of each row
a.sum(axis=1)

array([181, 254, 202])

In [50]:
a.mean(axis=1)

array([45.25, 63.5 , 50.5 ])

In [51]:
# gives maximum element in each row
a.max(axis=1)

array([54, 73, 90])

In [52]:
# gives index of maximum element in each row
a.argmax(axis=1)

array([0, 0, 2], dtype=int64)

In [53]:
a.argmax()

10