In [1]:
# working with python modules

In [1]:
import numpy

In [1]:
import myfile

myfile.abc()

Good morning


In [2]:
import keyword
keyword.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [5]:
from keyword import kwlist,iskeyword

In [6]:
iskeyword('if')

True

In [4]:
import numpy as np

In [11]:
a = np.array([3,4,5,6,7])
a

array([3, 4, 5, 6, 7])

In [12]:
len(a)

5

In [13]:
type(a)

numpy.ndarray

In [14]:
a.dtype

dtype('int32')

In [15]:
a.shape

(5,)

In [16]:
a.size

5

In [17]:
a.ndim

1

In [18]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
a.ndim

2

In [20]:
a.shape

(2, 3)

In [21]:
a.size

6

In [22]:
a = np.array([[[1,2],[2,3],[3,4]],[[1,2],[2,3],[3,4]],[[1,2],[2,3],[3,4]],[[1,2],[2,3],[3,4]]])
a

array([[[1, 2],
        [2, 3],
        [3, 4]],

       [[1, 2],
        [2, 3],
        [3, 4]],

       [[1, 2],
        [2, 3],
        [3, 4]],

       [[1, 2],
        [2, 3],
        [3, 4]]])

In [23]:
a.ndim

3

In [24]:
a.shape

(4, 3, 2)

In [25]:
a.sum(axis=1)

array([[6, 9],
       [6, 9],
       [6, 9],
       [6, 9]])

In [26]:
a.mean(axis=1)

array([[2., 3.],
       [2., 3.],
       [2., 3.],
       [2., 3.]])

In [28]:
a[0]

array([[1, 2],
       [2, 3],
       [3, 4]])

In [29]:
a[0][1]

array([2, 3])

In [5]:
c=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
c[0:2, -1]

array([3, 6])

In [36]:
c[0:2, -1:]

array([[3],
       [6]])